### ISSUE TITLE
Reduce the size of the index on large documentation site

### ISSUE THREAD

**Issue by Mogztter** [Mogztter/antora-lunr#2]
The Lunr index can quickly weight a few megabytes. Since the client will have to download this file, we need to find solution to reduce the size of this file.

Using compression https://github.com/nodeca/pako ?

**Comment by lpetit-yseop** [comment]
After having updated to `0.4.0` which includes this feature, and having adapted the URL of the search index file in the frontend (from `search_index.json` to `search_index.json.gz`), I have a problem in the frontend, it seems like it's not able to interpret the gzip file. Is there something I need to do in the frontend code?

**Comment by Mogztter** [comment]
@lpetit-yseop Do you use a (local) web server to serve your document site ? Do you have any error on the client (ie. JavaScript console) ?

**Comment by Mogztter** [comment]
I think I need to update the frontend to decompress the file using Pako.

**Comment by Mogztter** [comment]
I've updated the README.
You now have to configure a `supplemental_ui` directory (provided). As a result you should now use the default UI: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable

Let me know if it's working.

**Comment by lpetit-yseop** [comment]
> Let me know if it's working.

I had to adapt locally. But it does not seem to work. Complaining in `search.js` about `pako` being undefined.

**Comment by Mogztter** [comment]
It's working fine on my proof-of-concept. The file is here: https://github.com/Mogztter/antora-lunr/blob/master/supplemental_ui/js/vendor/pako.min.js and referenced here: 
https://github.com/Mogztter/antora-lunr/blob/b46ec8b92490d3c5cb838216a4360f7bc6a4325e/supplemental_ui/partials/footer-scripts.hbs#L9

Is your documentation project open-source ?

**Comment by lpetit-yseop** [comment]
Unfortunately, it's not open-source.
I am trying to work around this by keeping the `search.js` file, leveraging `gulp` dependencies for `lunr` and `pako`.
I am adding this directly inside our modified Antora UI bundle.

When I have something working I'll let you know. Stay tuned!

**Comment by lpetit-yseop** [comment]
It's now working.
But I embedded things inside our own version of the Antora default UI.
What I did differently is:

- Added a "dependencies" section to `package.json`:
```json
"dependencies": {
  "lunr": "^2.3.6",
  "pako": "^1.0.10"
}	  
```

- Added the `search.css` via an import in the existing `site.css`:
```css
@import "search.css";
```

- Used `require()` in the top of the `search.js` file to have gulp create a minified `search.js` at build time:
```javascript
var lunr = (window.lunr = require('lunr'));
var pako = (window.pako = require('pako'));
[…]
```

- Removed those explicit imports of lunr and pako from `footer-scripts.hbs`:
```javascript
<script src="{{uiRootPath}}/js/vendor/lunr.js"></script>	
<script src="{{uiRootPath}}/js/vendor/pako.min.js"></script>
```

- No need anymore to explicitly import the `search.css`, since it is embedded, minified, with the global `site.css`. This means the file `head-meta.hbs` is empty in my version.

**Comment by Mogztter** [comment]
Thanks for the detailed explanation. Hopefully it will help someone else to integrate this plugin directly in their own version of the Antora default UI.

In theory, if you use the `supplemental_ui` directory it should work. Could you confirm that you didn't try this approach ? Otherwise I may have missed something.

Anyway, if you want to integrate this plugin directly in the Antora Default UI then you did exactly what was needed 👍

**Comment by lpetit-yseop** [comment]
Thanks.
I did also try using `supplemental_ui`, but I didn't push real hard so maybe it works and I should have pushed a little bit harder.

**Comment by mojavelinux** [comment]
I don't think it's a good idea to be compressing the index manually. This is something that's already built into HTTP negotiation, and it's a heck of a lot faster. You are only tricking yourself into thinking that doing manual compression is better because it looks better on disk. Of course, you could still gzip on the server for storage purposes (so that part is okay), but with the right headers, the browser should be able to uncompress it itself. Plus, you cut out having to load an extra library (pako.js).

If you really want to reduce the index size, I would focus on indexing less things in the page. Perhaps you don't need every last paragraph or table cell.

**Comment by Mogztter** [comment]
What about something like:

**partials/footer-scripts.hbs**
```html
<script src="../../_/../search_index.js"></script>
<script>antoraLunr.init(antoraLunr.data)</script>
```

**search_index.js**
```js
window.antoraLunr.data = {"index": "..."}
```

And then gzip the `search_index.js` file on the server and use aggressive cache options.

@mojavelinux I believe that this is what you had in mind ?

**Comment by danyill** [comment]
The asynchronous load improves performance dramatically -- prior to this I had about a 3-5s hang on my Antora website after every page load with the latest release. Thanks @Mogztter

**Comment by Mogztter** [comment]
Awesome, did you enable compression on the server side (gzip) ?

**Comment by danyill** [comment]
Nope I was using node-srv but I did try it with the local filesystem as well and it was nice that it worked (although I think re-loads all the javascript every time?).

**Comment by Mogztter** [comment]
> although I think re-loads all the javascript every time

Yes, the JavaScript will be loaded on each page but that was already the case.
The nice thing about using a web server is that you can enable an aggressive caching and compression so the index will be fetched from the server only once. Then the file will be fetched from the cache.

On a local filesystem, I think most of the time is spent creating the index with Lunr.
